web_server_location       = "North Europe"
web_server_rg             = "Myresourcegroup"
resource_prefix           = "web-server"
web_server_address_space  = "1.0.0.0/22"
web_server_address_prefix = "1.0.1.0/24"
web_server_name           = "web-01"